//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlipFace.Service.BlipFaceWebServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BlipFaceWebServices.ICountUseBlipFace")]
    public interface ICountUseBlipFace {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountUseBlipFace/Notify", ReplyAction="http://tempuri.org/ICountUseBlipFace/NotifyResponse")]
        void Notify(string guid, string version);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICountUseBlipFaceChannel : BlipFace.Service.BlipFaceWebServices.ICountUseBlipFace, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CountUseBlipFaceClient : System.ServiceModel.ClientBase<BlipFace.Service.BlipFaceWebServices.ICountUseBlipFace>, BlipFace.Service.BlipFaceWebServices.ICountUseBlipFace {
        
        public CountUseBlipFaceClient() {
        }
        
        public CountUseBlipFaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CountUseBlipFaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountUseBlipFaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountUseBlipFaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Notify(string guid, string version) {
            base.Channel.Notify(guid, version);
        }
    }
}
